orders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'add_order/$', views.add_order, name="add_order"),
    url(r'^$', views.adm_orders, name="adm_orders"),
    url(r'user_orders/(?P<elem_id>\w+)/$', views.user_orders, name="user_orders"),
    url(r'delfrombasket/(?P<elem_id>\w+)/$', views.del_from_basket, name="delfrombasket"),
    url(r'order_list/$', views.order_list, name="order_list"),
    url(r'order_items/$', views.order_items, name="order_items"),
    url(r'adm_ord_prod_items/$', views.adm_ord_prod_items, name="adm_ord_prod_items"),
    url(r'ord_editing/$', views.ord_editing, name="ord_editing"),
    url(r'ord_editing_save/$', views.ord_editing_save, name="ord_editing_save"),
    url(r'ord_editing_del/$', views.ord_editing_del, name="ord_editing_del"),
    url(r'ord_editing_list/$', views.ord_editing_list, name="ord_editing_list"),
    url(r'ord_del_product/$', views.ord_del_product, name="ord_del_product"),
    url(r'ord_edit_product/$', views.ord_edit_product, name="ord_edit_product"),
    url(r'order_recount/$', views.order_recount, name="order_recount"),
    url(r'ord_find_product/$', views.ord_find_product, name="ord_find_product"),
    url(r'size_for_product/$', views.size_for_product, name="size_for_product"),
    url(r'description_for_product/$', views.description_for_product, name="description_for_product"),
    url(r'adding_product_in_order/$', views.adding_product_in_order, name="adding_product_in_order"),
    url(r'sessionFalse/$', views.session_false, name="sessionFalse"),
    # url(r'foto_add/$', views.add_img, name="add_img"),
]

products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^product_save/$', views.adm_product_save, name="product_save"),
    # url(r'^adm_img/$', views.adm_product_img),
    url(r'^$', views.adm_products, name="adm_products"),
    url(r'product/(?P<product_id>\w+)/$', views.product, name="product"),
    url(r'product_by_category/(?P<category_id>\w+)/$', views.product_by_category, name="product_by_category"),
    url(r'all_product/$', views.all_product, name="all_product"),
    url(r'^brands/$', views.brands, name="brands"),
    url(r'^brand/(?P<brand_id>\w+)/$', views.brand, name="brand"),
    url(r'^baraholka/$', views.baraholka, name="baraholka"),
    url(r'^adm_products_img_add/$', views.adm_products_img_add, name="adm_products_img_add"),
    url(r'^image_product_del/$', views.image_product_del, name="image_product_del"),
    url(r'^adding_fabric/$', views.adding_fabric, name="adding_fabric"),
    url(r'^adding_product_cat/$', views.adding_product_cat, name="adding_product_cat"),
    url(r'^adm_new_products/$', views.adm_new_products, name="adm_new_products"),
    url(r'^adm_sizes_for_new_products/$', views.adm_sizes_for_new_products, name="adm_sizes_for_new_products"),
]

project_shop_bike/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    # url(r'^login/', include('landing.urls')),
    url(r'^profile/', include('landing.urls')),
    url(r'^admin_product/', include('products.urls')),
    url(r'^orders/', include('orders.urls')),

]\
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models


class Fabric(models.Model):
    name = models.CharField(max_length=64)
    short_description = models.TextField(max_length=256, blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    logo = models.ImageField(upload_to='logo/', blank=True)

    class Meta:
        # django само определяет единственное и множественное число, но можно переопределить
        verbose_name = "Фабрика"  # приомзносимое имя в единственном числе
        verbose_name_plural = "Фабрики"  # приомзносимое имя во множественном числе

    def __str__(self):  # настройка презинтации модели вадминке
        return "%s" % self.name

    def __unicode__(self):
        return self.logo.url


class ProductCategory(models.Model):
    name = models.CharField(max_length=64)
    is_activ = models.BooleanField(default=True)

    class Meta:
        # django само определяет единственное и множественное число, но можно переопределить
        verbose_name = "Категория товара"  # приомзносимое имя в единственном числе
        verbose_name_plural = "Категория товаров"  # приомзносимое имя во множественном числе

    def __str__(self):  # настройка презинтации модели вадминке
        return "%s" % self.name


class ProductSizes(models.Model):
    name_size = models.CharField(max_length=5)

    class Meta:
        verbose_name = "Размер"  # приомзносимое имя в единственном числе
        verbose_name_plural = "Размеры"  # приомзносимое имя во множественном числе

    def __str__(self):  # настройка презинтации модели вадминке
        return "%s" % self.name_size


class Product(models.Model):  # модели принято называть в ед. числе
    name = models.CharField(max_length=64, unique=True)
    article = models.CharField(max_length=7, default="артикул", unique=True)
    # purchase_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)  # Цена закупки
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    # allowance = models.DecimalField(max_digits=4, decimal_places=2, blank=True, default=20)  # торговая надбавка
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    short_description = models.TextField(max_length=128, blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    prod_active = models.BooleanField(default=True)
    year_model = models.CharField(max_length=10, default="2018")
    status_new = models.BooleanField(default=True)
    status_sale = models.BooleanField(default=True)
    second_hands = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=True, auto_now=False)
    fabric = models.ForeignKey(Fabric, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    sizes = models.ManyToManyField(ProductSizes, blank=True, null=True, default=None)

    class Meta:
        # django само определяет единственное и множественное число, но можно переопределить
        verbose_name = "Товар"  # приомзносимое имя в единственном числе
        verbose_name_plural = "Товары"  # приомзносимое имя во множественном числе

    def __str__(self):  # настройка презинтации модели вадминке
        return "%s %s" % (self.price, self.name)


class ProductImage(models.Model):  # модели принято называть в ед. числе
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    image = models.ImageField(upload_to='product_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        # django само определяет единственное и множественное число, но можно переопределить
        verbose_name = "Фото"  # приомзносимое имя в единственном числе
        verbose_name_plural = "Фотографии"  # приомзносимое имя во множественном числе

    def __str__(self):  # настройка презинтации модели вадминке
        return "%s" % self.id

    def __unicode__(self):
        return self.image.url

products/views.py
from json import JSONDecodeError

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser
from django.core.serializers import json
from django.core.serializers.json import DjangoJSONEncoder
from django.db import transaction
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.utils.datastructures import MultiValueDictKeyError

from landing.forms import Login, UserCreation
from orders.forms import BasketForm
from .forms import ProductImageForm, ProductForm, AddingFabricForm, AddProductCatForm
from products.models import *
# import requests
import json


# adm_product (product.html)
@login_required
@transaction.atomic
def adding_fabric(request):
    args = dict()
    args.update(csrf(request))
    if request.POST and request.FILES:

        form = AddingFabricForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    elif request.POST:
        form = AddingFabricForm(request.POST)
        if form.is_valid():
            form.save()
    return redirect('/admin_product')


# adm_product (product.html)
@login_required
@transaction.atomic
def adding_product_cat(request):
    args = dict()
    args.update(csrf(request))
    if request.POST:
        form = AddProductCatForm(request.POST)
        if form.is_valid():
            form.save()
    return redirect('/admin_product')


# adm_product (product.html)
@login_required
@transaction.atomic
def adm_products(request):
    args = dict()
    args.update(csrf(request))

    args['products'] = Product.objects.all()

    args['form1'] = ProductForm(request.POST or None)
    args['form2'] = ProductImageForm()
    args['form3'] = AddingFabricForm()
    args['form4'] = AddProductCatForm()

    # if request.method == "GET":
    if request.POST:
        if request.POST.get('SearchProduct'):
            args['products'] = Product.objects.filter(article__contains=request.POST.get('SearchProduct'))
            if len(args['products']) == 0:
                args['products'] = Product.objects.filter(name__contains=request.POST.get('SearchProduct'))
                if len(args['products']) == 0:
                    args['products'] = Product.objects.all()
        else:
            try:
                article = request.POST.get('article')
                if Product.objects.filter(article=article).exists():

                    product = Product.objects.get(article=article)
                    args['form1'] = ProductForm(request.POST, instance=product)
                    print("наш запрос изменение", request)
                    if args['form1'].is_valid():
                        print("TUT TUT TUT", request.POST.get('sizes'))
                        nf = args['form1'].save(commit=False)
                        nf.save(force_update=True)
                        args['form1'].save_m2m()
                        return redirect('/admin_product')
                else:
                    print("наш запрос создание", request)
                    args['form1'] = ProductForm(request.POST)

                    if args['form1'].is_valid():
                        nf = args['form1'].save(commit=False)
                        nf.save()
                        args['form1'].save_m2m()
                        return redirect('/admin_product')

            except MultiValueDictKeyError:
                print("U_______________MultiValueDictKeyError")
            except:
                print("U_______________XZ___KeyError")
                return redirect('/admin_product')
    return render(request, 'products/product.html', args)


# adm_product (product.html)
@login_required
@transaction.atomic
def adm_new_products(request):
    args = dict()
    args.update(csrf(request))
    if request.POST and request.POST.get('article'):
        products = ProductImage.objects.filter(product__article=request.POST.get('article')).values(
            'id', 'product_id', 'product__article', 'product__category__name', 'product__name', 'product__fabric__name',
            'product__price', 'product__discount', 'product__year_model', 'product__prod_active', 'product__status_new',
            'product__status_sale', 'product__second_hands', 'product__short_description', 'product__description',
            'is_active', 'is_main', 'image'
        )
        if len(products) == 0:
            product = Product.objects.get(article=request.POST.get('article'))

            products = [
                {'product_id': product.id, 'product__name': product.name, 'product__article': product.article,
                 'product__category__name': product.category.name, 'product__fabric__name': product.fabric.name,
                 'product__price': product.price, 'product__discount': product.discount,
                 'product__year_model': product.year_model, 'product__prod_active': product.prod_active,
                 'product__status_new': product.status_new, 'product__status_sale': product.status_sale,
                 'product__second_hands': product.second_hands, 'product__short_description': product.short_description,
                 'product__description': product.description,
                 }
            ]
        json_orders_user = json.dumps(list(products), cls=DjangoJSONEncoder)
        return JsonResponse(json_orders_user, safe=False)
    return JsonResponse(False, safe=False)


# adm_product (product.html)
@login_required
@transaction.atomic
def adm_sizes_for_new_products(request):
    args = dict()
    args.update(csrf(request))
    if request.POST and request.POST.get('article'):
        sizes = ProductSizes.objects.filter(product__article=request.POST.get('article')).values('id', 'name_size')
        json_orders_user = json.dumps(list(sizes), cls=DjangoJSONEncoder)
        return JsonResponse(json_orders_user, safe=False)
    return JsonResponse(False, safe=False)


@login_required
@transaction.atomic
def adm_products_img_add(request):
    args = dict()
    args.update(csrf(request))
    if request.POST:
        # args['form2'] = ProductImageForm()
        args['form2'] = ProductImageForm(request.POST, request.FILES)
        if args['form2'].is_valid():
            args['form2'].save()
            # return render(request, 'products/product.html', args)
            return redirect('/admin_product')
    return redirect('/admin_product')


# sends js data to the output of pictures for the selected product (js:AutoProductList)
# @login_required
# @transaction.atomic
# def adm_product_img(request):
#     args = dict()
#     # args.update(csrf(request))
#     products_img_list = []
#     if request.POST:
#         name = request.POST.get('name')
#         for img in ProductImage.objects.filter(product__name=name):
#             products_img_list.append([img.image.url, img.is_main, img.is_active, img.id])
#
#         args['products_img_list'] = products_img_list
#         dumps = json.dumps(args)
#         return HttpResponse(dumps)


@login_required
@transaction.atomic
def image_product_del(request):
    args = dict()
    if request.POST:
        args.update(csrf(request))
        img = request.POST.get('img_for_del')
        del_img = ProductImage.objects.get(id=img)
        del_img.delete()
        print("удаление image_product_del")

    return redirect('/admin_product')


@login_required
@transaction.atomic
def adm_product_save(request):
    if request.method == "GET":
        json_data = request.GET
        list_img = {}
        for elem in json_data:
            if elem != "_":
                # json_data_elem = eval(elem) #  не воспринимает true & false
                # try:
                json_data_elem = json.loads(elem)
                for dic in json_data_elem:
                    if dic == "image_id":
                        for id in json_data_elem[dic]:
                            # print("image_id____________________image_id__", json_data_elem[dic][id],
                            #       "type elem ->", type(json_data_elem[dic][id]), end="\n")
                            fotka = ProductImage.objects.get(id=int(id))
                            fotka.is_main = json_data_elem[dic][id][0]
                            fotka.is_active = json_data_elem[dic][id][1]
                            fotka.save()

                    # else:
                    #     print("test____________________test", json_data_elem[dic],
                    #           "type elem ->", type(json_data_elem[dic]), end="\n")

    dumps = json.dumps("OK")
    return HttpResponse(dumps)


def product(request, product_id):
    product = Product.objects.get(id=product_id)
    # prod1 = product.productinbasket_set.values('price_per_item')
    if auth.get_user(request).username != AnonymousUser.username:
        user = auth.get_user(request)

    # else:
    #     user = False

    pr_img = ProductImage.objects.filter(product=product_id)
    # form = BasketForm(request.POST, instance=product)
    form = BasketForm(request.POST)
    if request.POST:
        form = BasketForm(request.POST)
        data = request.POST
        price_per_item = data.get('price_per_item')
        if form.is_valid():
            obj = form.save(commit=False)
            obj.session_key = request.session.session_key
            obj.product = product
            obj.price_per_item = price_per_item
            obj.save()
            return redirect("/admin_product/product/" + str(product_id))

    return render(request, 'products/us_product.html', locals())


def product_by_category(request, category_id):
    product_image = ProductImage.objects.filter(is_main=True, is_active=True, product__category=category_id,
                                                product__second_hands=False)
    return render(request, 'products/products_by_category.html', locals())


def all_product(request):

templates/products/product.html
{#{% extends 'landing/home.html' %}#}
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}

    <div class="product-item">
        <div class="row">
            <div class = "col-8">
                <div class="in_col_9">
                {# url 'product_save' - в url name=product_save #}
                <form id="form_product_change" action="{% url 'adm_products' %}" method="post" name="adm_product_form">
                    {% csrf_token %}
                    <div class="orange_div" id="adm-prod-article">
                        <label for="id_article">Артикул</label><br>
                        {{ form1.article }}
                    </div>
                    <div class="orange_div" id="adm-prod-category">
                        <label for="id_category">Category</label>
                        <button type="button" class="btn-danger mini_btn" href="javascript:" id="btn_mini_cat_new">
                            n e w</button><br>
                        {{ form1.category }}
                    </div>
                    <div class="orange_div" id="adm-prod-name">
                        <label for="id_name">name</label><br>
                        {{ form1.name }}
                    </div>
                    <div class="orange_div" id="adm-prod-fabric">
                        <label for="id_fabric">fabric</label>
                        <button type="button" class="btn-danger mini_btn" href="javascript:" id="btn_mini_fabric_new">
                            n e w</button><br>
                        {{ form1.fabric }}
                    </div>
                    <div class="orange_div" id="adm-prod-year_model">
                        <label for="id_year_model">year_model</label><br>
                        {{ form1.year_model }}
                    </div>
                    <div class="orange_div" id="adm-prod-price">
                        <label for="id_price">price</label><br>
                        {{ form1.price|safe }}
                    </div>
                    <div class="orange_div" id="adm-prod-discount">
                        <label for="id_discount">discount</label><br>
                        {{ form1.discount|safe }}
                    </div>
                    <div class="orange_div" id="adm-prod-sizes">
                        <label for="id_sizes">Sizes</label><br>
                        {{ form1.sizes }}
                    </div>
                    <div class="orange_div" id="adm-prod-description">
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active ">
                                <a href="#short_description" aria-controls="home" role="tab" data-toggle="tab"
                                   class="my-tabs">Краткое описание</a>
                            </li>
                            <li role="presentation"><a href="#description" class="my-tabs" aria-controls="profile"
                                                       role="tab" data-toggle="tab">Полное описание</a>
                            </li>
                        </ul>
                        <div class="tab-content product-description-tabs">
                            <div role="tabpanel" class="tab-pane active" id="short_description">
                                {{ form1.short_description }}
                            </div>
                            <div role="tabpanel" class="tab-pane" id="description">
                                {{ form1.description }}
                            </div>
                        </div>
                    </div>
                    <div class="orange_div" id="id-active">
                        active<br>
                     {{ form1.prod_active|add_class:"check_fild" }}
                    </div>
                    <div class="orange_div" id="id-status_sale">
                        Sale<br>
                    {{ form1.status_sale|add_class:"check_fild" }}
                    </div>
                    <div class="orange_div" id="id-status_new">
                        New<br>
                    {{ form1.status_new|add_class:"check_fild" }}
                    </div>
                    <div class="orange_div" id="id-second_hands">
                        Second Hand<br>
                    {{ form1.second_hands|add_class:"check_fild" }}
                    </div>
                    <button type="submit" class="btn btn-outline my-2 my-sm-0 hidediv" href="javascript:"
                            id="change-product">Перекроить</button>
                    <button type="submit" class="btn btn-outline my-2 my-sm-0" href="javascript:"
                            id="btn_adding-product">Добавить новый продукт</button>
                </form>
                </div>
                <div id="id_img-adm" class="line-img orange_div">
                    <!-- Заполняется из js-->
{#                    <img src="/madia/product_images/LS2OF562_Pink.jpg" class='img-adm'>#}
                </div>
                <button type="button" class="btn btn-outline my-2 my-sm-0 hidediv" id="btn_add-show-img_block"
                        href="javascript:">Добавить картинку</button>

            </div>
            <div class = "col-4 orange_div" id="product_list">
                <div id="div-find-product">
                    <form action="" name="find_product" id="form-find-product" method="post">
                        {% csrf_token %}
                        <input name="SearchProduct" type="search" class="search-label-icon">
                        <button type="submit" class="btn btn-outline my-2 my-sm-0"
                                style="position: relative; top: 1vh"
                        >Искать</button>
                    </form>
                </div>

                <table class="table text-left">
                    <thead>
                        <tr>
                            <th>Article</th>
                            <th>Product</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in products %}
                            <tr>
                            <td>

                            <a href="javascript:" class="product_list" data-article="{{ product.article }}"
                                > {{ product.article }}</a><br>
                            </td>
                            <td>
                                {{ product.name }}
                            </td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
        <div class = "orange_div hidediv b-popup" id="div-prod-form-img">
            <div class="orange_div" id="div-prod-form-img-content">
                <form id="form_img_add" method="POST" action="{% url 'adm_products_img_add' %}"
                      enctype="multipart/form-data">{% csrf_token %}
    {#                    {% render_field form2.product type="hidden" %}#}
    {#                    {{ form2.instance.product }}#}
{#                    {{ form2.product }}#}
                    {{ form2.product| add_class:"HiddenInput" }}
                    {{ form2.image }}<br>
                    основная {{ form2.is_main }}
                    активная {{ form2.is_active }}
                    <button type="submit" class="btn btn-outline my-2 my-sm-0 pos_btns_add_img" id="create-img">
                        Добавить картинку</button>
                    <button type="button" class="btn btn-outline my-2 my-sm-0 pos_btns_add_img" id="btn_end-create-img">
                        Выйти</button>
                </form>
            </div>
        </div>
{#    /////////////////////////////////////////Hiden div for large image and delete#}
        <div class="orange_div hidediv b-popup" id="div-del-img">
            <div class="orange_div" id="div-del-img-cont">
            <form action="{% url 'image_product_del' %}" method="post">
                {% csrf_token %}
                <input hidden type="number" name="img_for_del" id="id_img_for_del">
                <div id="show_img_for_del">
                    <!-- Заполняется из js-->
                </div><br>
                <div class="block_btn_img_del">
                <button type="submit" class="btn btn-outline my-2 my-sm-0" >Удалить картинку</button>
                <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_cancel-del-img" href="javascript:">
                    Выйти</button>
                </div>
            </form>
            </div>
        </div>
{#    /////////////////////////////////////////Hiden div for adding fabric#}
        <div class="orange_div hidediv b-popup" id="div-adding_fabric">
            <div class="orange_div" id="div-adding_fabric_cont">
                <h3>Добавить производителя</h3>
                <form action="{% url 'adding_fabric' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form3.as_p }}

                    <button type="submit" class="btn btn-outline my-2 my-sm-0" >Добавить</button>
                    <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_cancel_add_fabric"
                            href="javascript:">Выйти</button>
                </form>
            </div>
        </div>
{#    /////////////////////////////////////////Hiden div for adding category of product#}
        <div class="orange_div hidediv b-popup" id="div-adding_product_category">
            <div class="orange_div" id="div-adding_product_category_cont">
                <h3>Добавить категорию товара</h3>
                <form action="{% url 'adding_product_cat' %}" method="post">
                    {% csrf_token %}
                    {{ form4.as_p }}

                    <button type="submit" class="btn btn-outline my-2 my-sm-0" >Добавить</button>
                    <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_cancel_add_prod_cat"
                            href="javascript:">Выйти</button>
                </form>
            </div>
        </div>

    </div>

{% endblock %}

templates/products/us_product.html
{% extends 'wrapper.html' %}
{% load static %}
{% load mathfilters %}
{% load i18n %}
{% load widget_tweaks %}

{% block user_content %}
    <div class="col-7">
        <div class="us-product-view">
            <div class="row">
                <div class="col-4">
                    <div>
                        {% for img in pr_img %}
                            <img src="{{ img.image.url }}" class="center-block img-full-size-block">
                        {% endfor %}
                    </div>
                </div>
                <div class="col-8">
                    <h3>{{ product.category }}</h3>
                    <h3>{{ product.name }}</h3><br>
                    <h4> Артикл - {{ product.article }}</h4><br>
                    <h4> Производство - {{ product.fabric }}</h4><br>
{#                    <h5>{{ product.description }}</h5><br><br>#}
                    <div>

                    {% if product.discount %}
                        <h5> Цена - {{ product.price }}</h5><br>
                        <div class="line-draw-item"></div>
                        <h4> Cкидка на товар- {{ product.discount }} %
                        {% if user and user.profile.discount %}
                            + Ваша скидка- {{ user.profile.discount }} %</h4><br>
                            <h4>Цена -
                            {{ 100|sub:product.discount|sub:user.profile.discount|div:100|mul:product.price|floatformat:"-2" }}
                        {% else %}
                            <h4>Цена - {{ 100|sub:product.discount|div:100|mul:product.price|floatformat:"-2" }}
                        {% endif %}
                            </h4><br>


                     {% else %}
                        <h4> Цена - {{ product.price }}</h4><br><br>
                    {% endif %}
                    </div>
                    <h4> Размеры в наличии</h4> <br>
                    <h4>{% for tag in product.sizes.all %}
                         {{ tag }},
                    {% endfor %}</h4><br>
                    <form action="" method="post" id="form_buying_product">{% csrf_token %}
                        <label for="id_sizes">Выберете размер</label><br>

                        <select id="select-size">
                        <h4>{% for tag in product.sizes.all %}
                            <option>{{ tag }}</option>
                        {% endfor %}
                        </select></h4><br>

                        {{ form.sizes|attr:"class:hiddem_forms_fild" }}<br>
                        {{ form.nmb }}

                        {{ form.price_per_item|attr:"class:hiddem_forms_fild" }}
                        {% if user and user.profile.discount %}
                          <button type="submit" class="btn btn-outline my-2 my-sm-0" id="btn-by"
                            data-price_per_itm="{{ 100|sub:product.discount|sub:user.profile.discount|div:100|mul:product.price }}"
                          >Бросить в тележку</button>
                        {% else %}
                          <button type="submit" class="btn btn-outline my-2 my-sm-0" id="btn-by"
                            data-price_per_itm="{{ 100|sub:product.discount|div:100|mul:product.price }}"
                          >Бросить в тележку</button>
                        {% endif %}
                    </form>
                <p style="word-break: break-all; color: white; white-space: pre-wrap; padding: 1vw; font-size: 1.3vw">{{ product.description }}</p><br><br>
                </div>
            </div>

        </div>
    </div>

{% endblock %}