orders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'add_order/$', views.add_order, name="add_order"),
    url(r'^$', views.adm_orders, name="adm_orders"),
    url(r'user_orders/(?P<elem_id>\w+)/$', views.user_orders, name="user_orders"),
    url(r'delfrombasket/(?P<elem_id>\w+)/$', views.del_from_basket, name="delfrombasket"),
    url(r'order_list/$', views.order_list, name="order_list"),
    url(r'order_items/$', views.order_items, name="order_items"),
    url(r'adm_ord_prod_items/$', views.adm_ord_prod_items, name="adm_ord_prod_items"),
    url(r'ord_editing/$', views.ord_editing, name="ord_editing"),
    url(r'ord_editing_save/$', views.ord_editing_save, name="ord_editing_save"),
    url(r'ord_editing_del/$', views.ord_editing_del, name="ord_editing_del"),
    url(r'ord_editing_list/$', views.ord_editing_list, name="ord_editing_list"),
    url(r'ord_del_product/$', views.ord_del_product, name="ord_del_product"),
    url(r'ord_edit_product/$', views.ord_edit_product, name="ord_edit_product"),
    url(r'order_recount/$', views.order_recount, name="order_recount"),
    url(r'ord_find_product/$', views.ord_find_product, name="ord_find_product"),
    url(r'size_for_product/$', views.size_for_product, name="size_for_product"),
    url(r'description_for_product/$', views.description_for_product, name="description_for_product"),
    url(r'adding_product_in_order/$', views.adding_product_in_order, name="adding_product_in_order"),
    url(r'sessionFalse/$', views.session_false, name="sessionFalse"),
    # url(r'foto_add/$', views.add_img, name="add_img"),
]

project_shop_bike/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    # url(r'^login/', include('landing.urls')),
    url(r'^profile/', include('landing.urls')),
    url(r'^admin_product/', include('products.urls')),
    url(r'^orders/', include('orders.urls')),

]\
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.contrib.auth.models import User
from django.db import models

from products.models import Product


class StatusOrder(models.Model):  # модели принято называть в ед. числе
    status_name = models.CharField(max_length=24)
    status_is_actual = models.BooleanField(default=True)

    class Meta:
        # django само определяет единственное и множественное число, но можно переопределить
        verbose_name = "Статус заказа"  # приомзносимое имя в единственном числе
        verbose_name_plural = "Статусы заказа"  # приомзносимое имя во множественном числе

    def __str__(self):  # настройка презинтации модели вадминке
        return self.status_name


class Order(models.Model):  # модели принято называть в ед. числе
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)  # total price for all products in order
    customer_name = models.CharField(max_length=64, blank=False, verbose_name="Как звать?")
    # customer_email = models.EmailField(blank=True, null=True)
    customer_phone = models.CharField(max_length=48, blank=False, verbose_name="Мобила для связи")
    customer_address = models.CharField(max_length=128, blank=True, null=True, verbose_name="Куда везти?")
    comments = models.TextField(max_length=256, blank=True, verbose_name="Что еще нам стоит знать?")
    status_ord = models.ForeignKey(StatusOrder, null=True, on_delete=models.SET_NULL, default="created")
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)
    data_completed = models.DateField(blank=True, null=True)

    class Meta:
        # django само определяет единственное и множественное число, но можно переопределить
        verbose_name = "Заказ"  # приомзносимое имя в единственном числе
        verbose_name_plural = "Заказы"  # приомзносимое имя во множественном числе

    def __str__(self):  # настройка презинтации модели вадминке
        return "Заказ  %s %s" % (self.id, self.status_ord.status_name)


class ProductInBasket(models.Model):
    session_key = models.CharField(max_length=128)
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    nmb = models.PositiveSmallIntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    sizes = models.CharField(max_length=128, blank=True)
    # total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)  # price*nmb

    class Meta:
        verbose_name = "Товар в корзине"  # приомзносимое имя в единственном числе
        verbose_name_plural = "Товары в корзине"  # приомзносимое имя во множественном числе

    # def save(self, *args, **kwargs):
    #     self.price_per_item = self.product.price
    #     self.total_price = int(self.nmb) * self.price_per_item
    #
    #     super(ProductInBasket, self).save(*args, **kwargs)

orders/forms.py
from django import forms
from django.forms import Textarea, NumberInput

from .models import *


class BasketForm(forms.ModelForm):

    class Meta:
        model = ProductInBasket
        fields = '__all__'
        # widgets = {'session_key': forms.HiddenInput}

    def __init__(self, *args, **kwargs):
        super(BasketForm, self).__init__(*args, **kwargs)
        self.fields['session_key'].required = False
        self.fields['price_per_item'].required = False


class AddOrder(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

        widgets = {'User': forms.HiddenInput,
                   # 'status_ord': forms.Select(attrs={'disabled': True}),
                   # 'status_ord': forms.HiddenInput,
                   # 'total_price': forms.NumberInput(attrs={'disabled': True})
                   }

    def __init__(self, *args, **kwargs):
        super(AddOrder, self).__init__(*args, **kwargs)
        self.fields['total_price'].required = False
        self.fields['status_ord'].required = False


class AdmProductInOrder(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class DateInput(forms.DateInput):
    input_type = 'date'


class OrderAdmOrders(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

    # def __init__(self, *args, **kwargs):
    #     super(OrderAdmOrders, self).__init__(*args, **kwargs)
    #     self.fields['data_completed'].widget = widgets.AdminSplitDateTime()
        widgets = {'data_completed': DateInput(),
                   'comments': Textarea(attrs={'cols': 30, 'rows': 4, 'placeholder': "Что нам надо знать"}),
                   'customer_address': Textarea(attrs={'cols': 30, 'rows': 2, 'placeholder': "Введите адрес"}),
                   }

orders/views.py
import simplejson as simplejson
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.serializers import json
import json
from django.contrib.auth.models import AnonymousUser, User
from django.core.serializers.json import DjangoJSONEncoder
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, render_to_response
from django.template.context_processors import csrf

from orders.forms import AddOrder, OrderAdmOrders
from orders.models import ProductInBasket, Order, StatusOrder
from products.models import ProductImage, ProductSizes, Product

from decimal import Decimal


# (Orders) < --Sends data to js to output products according to the selected order (js:AddProductToOrder())
@login_required
@transaction.atomic
def adding_product_in_order(request):
    args = {}
    if request.POST:
        args.update(csrf(request))
        price_per_item = Decimal(request.POST.get('price_per_item'))
        nmb = Decimal(request.POST.get('nmb'))
        product_id = request.POST.get('product_id')
        product = Product.objects.get(id=product_id)
        size = request.POST.get('size')
        if request.POST.get('order_ord'):
            sessionkey = request.session.session_key
            order = Order.objects.get(id=request.POST.get('order_ord'))
            prod_in_bask = ProductInBasket()
            prod_in_bask.order = order
            prod_in_bask.product = product
            prod_in_bask.nmb = nmb
            prod_in_bask.price_per_item = price_per_item
            prod_in_bask.sizes = size
            prod_in_bask.session_key = str(auth.get_user(request).username) + sessionkey
            prod_in_bask.save(auth.models.User.username)
            order.total_price = order.total_price + (price_per_item * nmb)
            order.save(force_update=True)
            products = ProductImage.objects.filter(product__productinbasket__order=order, is_main=True).values(
                'image', 'product__article', 'product__name', 'product__productinbasket__sizes',
                'product__productinbasket__nmb', 'product__productinbasket__price_per_item', 'product__productinbasket',
                'product__price'
            )
            json_orders_user = json.dumps(list(products), cls=DjangoJSONEncoder)
            return JsonResponse(json_orders_user, safe=False)
    return JsonResponse(False, safe=False)


# (Orders) < --(js:sessionfalse())
@login_required
@transaction.atomic
def session_false(request):
    args = {}
    args.update(csrf(request))
    request.session['pk'] = False
    return HttpResponse('OK')


# (Orders) < --Displays the main order page. Processes a query from a form for data filtering
@login_required
@transaction.atomic
def adm_orders(request):
    # request.session['pk'] = False
    args = {}
    args['orders'] = Order.objects.filter(status_ord__status_name="created")
    # args['orders'] = Order.objects.all()
    args['order_form'] = OrderAdmOrders()
    args['users'] = User.objects.all()
    args['status_ord'] = StatusOrder.objects.all()
    args['products'] = ProductImage.objects.filter(is_main=True, is_active=True)
    args['all_cust_name'] = set()
    for elem in args['orders'].values_list('customer_name'):
        args['all_cust_name'].add(elem[0])

    if request.POST:
        args.update(csrf(request))
        id_ord = request.POST.get('nord')
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        create = request.POST.get('create')
        completed = request.POST.get('completed')
        user = request.POST.get('user')
        status = request.POST.get('status')

        if id_ord:
            args['orders'] = Order.objects.filter(id=id_ord)
        elif user and create and status:
            args['orders'] = Order.objects.filter(user__username=user, created__gte=create, status_ord__status_name=status)
        elif name and create and status:
            args['orders'] = Order.objects.filter(customer_name__contains=name, created__gte=create, status_ord__status_name=status)
        elif phone and create and status:
            args['orders'] = Order.objects.filter(customer_phone__contains=phone, created__gte=create, status_ord__status_name=status)
        elif user and status:
            args['orders'] = Order.objects.filter(user__username=user, status_ord__status_name=status)
        elif name and status:
            args['orders'] = Order.objects.filter(customer_name__contains=name, status_ord__status_name=status)
        elif phone and status:
            args['orders'] = Order.objects.filter(customer_phone__contains=phone, status_ord__status_name=status)
        elif user and create:
            args['orders'] = Order.objects.filter(user__username=user, created__gte=create)
        elif name and create:
            args['orders'] = Order.objects.filter(customer_name__contains=name, created__gte=create)
        elif phone and create:
            args['orders'] = Order.objects.filter(customer_phone__contains=phone, created__gte=create)

        elif user:
            args['orders'] = Order.objects.filter(user__username=user)
        elif name:
            args['orders'] = Order.objects.filter(customer_name__contains=name)
        elif phone:
            args['orders'] = Order.objects.filter(customer_phone__contains=phone)
        elif create:
            args['orders'] = Order.objects.filter(created__gte=create)
        elif completed:
            args['orders'] = Order.objects.filter(data_completed__gte=completed)
        elif status:
            args['orders'] = Order.objects.filter(status_ord__status_name=status)
        else:
            args['orders'] = Order.objects.all()
    return render(request, 'orders/orders.html', args)


# (Orders) < --Filter products according to the received query from js to add to the order (js:ProductFind)
@login_required
@transaction.atomic
def ord_find_product(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        if request.POST.get('product'):
            position = request.POST.get('product')
            product = ProductImage.objects.filter(product_id=position, is_main=True, is_active=True).values(
                'image', 'product', 'product__price', 'product__sizes__name_size', 'product__article',
                'product__category__name', 'product__name', 'product__fabric__name', 'product__year_model',
                'product__discount'
            )
            json_orders_user = json.dumps(list(product), cls=DjangoJSONEncoder)
            return JsonResponse(json_orders_user, safe=False)
        elif request.POST.get('article'):
            position = request.POST.get('article')
            product = ProductImage.objects.filter(product__article__contains=position, is_main=True, is_active=True).values(
                'image', 'product', 'product__price', 'product__article',
                'product__category__name', 'product__name', 'product__fabric__name', 'product__year_model',
                'product__discount'
            )
            json_orders_user = json.dumps(list(product), cls=DjangoJSONEncoder)
            return JsonResponse(json_orders_user, safe=False)
        elif request.POST.get('prod'):
            position = request.POST.get('prod')
            product = ProductImage.objects.filter(product__name__contains=position , is_main=True, is_active=True).values(
                'image', 'product', 'product__price', 'product__article',
                'product__category__name', 'product__name', 'product__fabric__name', 'product__year_model',
                'product__discount'
            )
            json_orders_user = json.dumps(list(product), cls=DjangoJSONEncoder)
            return JsonResponse(json_orders_user, safe=False)
        else:
            product = ProductImage.objects.filter(is_main=True, is_active=True).values(
                'image', 'product', 'product__price', 'product__article',
                'product__category__name', 'product__name', 'product__fabric__name', 'product__year_model',
                'product__discount'
            )
            json_orders_user = json.dumps(list(product), cls=DjangoJSONEncoder)
            return JsonResponse(json_orders_user, safe=False)
    return JsonResponse(False, safe=False)


# (Orders) < -- Sends in js the available sizes for the selected product (js: SelectedIdProduct)
@login_required
@transaction.atomic
def size_for_product(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        if request.POST.get('prod_id'):
            prod = request.POST.get('prod_id')
            sizes = ProductSizes.objects.filter(product=prod).values('name_size')

            json_orders_user = json.dumps(list(sizes), cls=DjangoJSONEncoder)
            return JsonResponse(json_orders_user, safe=False)
        return JsonResponse(False, safe=False)


# (Orders) < -- Sends in js description for the selected product (js: SelectedIdProduct)
@login_required
@transaction.atomic
def description_for_product(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        if request.POST.get('prod_id'):
            prod = request.POST.get('prod_id')
            description = Product.objects.get(id=prod).description
            # json_orders_user = json.dumps(list(description), cls=DjangoJSONEncoder)
            # return JsonResponse(json_orders_user, safe=False)
            return HttpResponse(description)
        return JsonResponse(False, safe=False)


# (Orders) < -- Sends data to js to fill in the attributes of the order form (js: ord_filter)
@login_required
@transaction.atomic
def ord_editing(request):
    args = {}
    args.update(csrf(request))
    orders_user = Order.objects.filter(id=request.POST.get('order')).values_list(
        'user', 'total_price', 'customer_name', 'customer_phone', 'status_ord', 'data_completed',

templates/orders/add_order.html
{% extends 'wrapper.html' %}
{% load static %}
{% load i18n %}

{% block user_content %}
    <div class="col-7">
        <div class="item-list">
            <h1>ТУТ ЗАКАЗ ОФОРМИМ</h1>
            <form action="" method="post" id="">{% csrf_token %}
                <label for="id_customer_name">Ваше имя</label>
                {{ form.customer_name }}<br>
                <label for="id_customer_phone">Ваш телефон</label>
                {{ form.customer_phone }}<br>
                <label for="id_customer_address">Адрес доставки</label>
                {{ form.customer_address }}<br>
                <label for="id_comments">Дополнительные пояснения</label><br>
                {{ form.comments }}<br>
{#                {{ form.status_ord }}#}
                <h3>Вего на сумму {{ amount }}</h3>
                <button type="submit" class="btn btn-outline my-2 my-sm-0">Отправить</button>
            </form>

        </div>
    </div>
{% endblock %}

templates/orders/add_order_adm.html
{#{% extends 'orders/orders.html' %}#}
{#{% load static %}#}
{##}
{#{% block addingOrders %}#}{#{% endblock %}#}

{#    <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_add_ok" href="javascript:">OK</button>#}
    <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_add_cancel" href="javascript:">Cancel</button><br><br>
    {{ request.session.pk }}
    <h1>Анекдот дня</h1>

templates/orders/order_prod_list.html
<div class="ord_prod_list">
    <h1>Список всех продуктов в заказе</h1>
    <div id="ord_prod_list_cont">
    <table class="table_prod_in_ord" cellspacing="2" border="1" cellpadding="5">
        <thead>
            <tr>
                <th>img</th>
                <th>article</th>
                <th width="350">product</th>
                <th width="70">count</th>
                <th width="100">price</th>
                <th width="100">size</th>
                <th width="20">KILL</th>
            </tr>
        </thead>
        <tbody class="">
            <tr>
            </tr>
        <div id="block_button">
        <!--js-button-->
        </div>
        </tbody>
    </table>
    </div>
    <div class="btns_ord_prodlist">
    <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_prod_add" href="javascript:">Добавить позицию</button>
    <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_list_cancel" href="javascript:">Выйти</button>
    </div>
</div>

templates/orders/orders.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="main_ord">
    <div class="row">
        <div class="col-8">

          <div class="orders-list scroll_ord">
            <div class="fix">

                <form action="" method="post">{% csrf_token %}
                    <div class="N-ord">
                        <label for="N-ord">№ ord.</label><br>
                        <input id="N-ord" name="nord">
                    </div>
                    <div class="id_user_f">
                        <label for="id_user_f">User</label><br>
                        <select id="id_user_f" name="user">
                            <option></option>
                            {% for elem in users %}
                                <option>{{ elem }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="id_customer_name_f">
                        <label for="id_customer_name_f">Name</label><br>
                        <select id="id_customer_name_f" name="name">
                            <option></option>
                            {% for elem in all_cust_name %}
                                <option>{{ elem }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="id_customer_phone_f">
                        <label for="id_customer_phone_f">Phone</label><br>
                        <input id="id_customer_phone_f" name="phone">
                    </div>
                    <div class="id_create_f">
                        <label for="id_create_f">Data create</label><br>
                        <input type="date" id="id_create_f" name="create">
                    </div>
                    <div class="id_data_completed_f">
                        <label for="id_data_completed_f">Data completed</label><br>
                        <input type="date" id="id_data_completed_f" name="completed">
                    </div>
                    <div class="id_status_ord_f">
                        <label for="id_status_ord_f">Status ord</label><br>
                        <select id="id_status_ord_f" name="status">
                            <option></option>
                            {% for elem in status_ord %}
                                <option>{{ elem }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button class="btn btn-outline my-2 my-sm-0" id="ord-filter">Фильтровать / Показать все</button>
                </form>
            </div>

            <table class="" cellspacing="2" border="1" cellpadding="5">
                <thead>
                    <tr class="visible0">
                        <th style="width: 3vw"></th>
                        <th style="width: 10vw"></th>
                        <th style="width: 7vw"></th>
                        <th style="width: 7vw"></th>
                        <th style="width: 12vw"></th>
                        <th style="width: 9vw"></th>
                        <th style="width: 7vw"></th>
                        <th style="width: 5vw"></th>
                    </tr>
                </thead>
                <tbody class="list">
                    {% for order in orders %}

                    <tr >

                        <td><a class="href_on_ord" data-ord_id="{{ order.pk }}" href="javascript:">{{ order.pk }}</a></td>
                        <td><a class="href_on_ord" data-ord_id="{{ order.pk }}" href="javascript:">{{ order.user }}</a></td>
                        <td><a class="href_on_ord" data-ord_id="{{ order.pk }}" href="javascript:">{{ order.customer_name }}</a></td>
                        <td><a class="href_on_ord" data-ord_id="{{ order.pk }}" href="javascript:">{{ order.customer_phone }}</a></td>
                        <td><a class="href_on_ord" data-ord_id="{{ order.pk }}" href="javascript:">{{ order.created }}</a></td>
                        <td><a class="href_on_ord" data-ord_id="{{ order.pk }}" href="javascript:">{{ order.data_completed }}</a></td>
                        <td><a class="href_on_ord" data-ord_id="{{ order.pk }}" href="javascript:">{{ order.status_ord }}</a></td>
                        <td><a class="href_on_ord" data-ord_id="{{ order.pk }}" href="javascript:">{{ order.total_price }}</a></td>

                    </tr>

                    {% endfor %}

                </tbody>
            </table>
          </div>
        </div>
        <div class="col-4">
            <div class="order_item">
                <form action="{% url 'ord_editing_save' %}" method="post" id="ord_editing">
                    {% csrf_token %}
                    <div id="ord_number_info"><h2></h2><h5></h5></div>
                    {% if request.session.pk == False %}
                        <input class="input_order_ord" hidden id="order_ord" name="order_id" >
                    {% else %}
                        <input class="input_order_ord" hidden id="order_ord" name="order_id" value="{{ request.session.pk }}">
                    {% endif %}
                    <div class="ord_user"><label for="id_user">User</label><br>{{ order_form.user }}</div>
                    <div class="ord_customer_name"><label for="id_customer_name">Имя</label><br>{{ order_form.customer_name }}</div>
                    <div class="ord_customer_phone"><label for="id_customer_phone">Телефон</label><br>{{ order_form.customer_phone }}</div>
                    <div class="ord_customer_address">{{ order_form.customer_address }}</div>
                    <div class="ord_comments">{{ order_form.comments }}</div>
                    <div class="ord_data_completed">{{ order_form.data_completed }}</div>
                    <div class="ord_status_ord">{{ order_form.status_ord }}</div>
                    <div class="ord_total_price"><label for="id_total_price">Сумма заказа</label><br>{{ order_form.total_price }}</div>
                    <br>
                    <button type="submit" class="btn btn-outline my-2 my-sm-0" id="btn_ord_edit">Изменить / Создать</button>
                </form>
                    <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_ord_calc" href="javascript:">calc</button>
                <form action="{% url 'ord_editing_del' %}" method="post" id="ord_del">
                    {% csrf_token %}
                    <input hidden id="order_ord_del" name="order_id_del">
                    <button type="submit" class="btn btn-outline my-2 my-sm-0" id="btn_ord_del">Удалить</button>
                </form>
            </div>
            <div class="nav-tabs" id="line_ord_form"></div>
            <div class="prod_list_ord">
                <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_prod_in_ord_list" href="javascript:">Список товаров в заказе</button>
                <button type="button" class="btn btn-outline my-2 my-sm-0" id="btn_create_ord" href="javascript:">Анекдот</button>
            </div>
        </div>
    </div>
    </div>
    <div id="add_block_list" class="add_block hidediv">
        <div class="add_block_content">
{#            <h1>Список товаров в заказе</h1>#}
            {% include 'orders/order_prod_list.html' %}
        </div>
    </div>

    {% if request.session.pk == False or not request.session.pk %}
        <div id="add_product" class="add_block hidediv">
    {% else %}
        <div id="add_product" class="add_block">
            <div id="Error_massage">
                <h3>Незакончена операция добавления товара в ордер № {{ request.session.pk }}</h3>
                <form action="{% url 'sessionFalse' %}">{% csrf_token %}
                <button type="submit" class="btn btn-outline my-2 my-sm-0" id="btn_session_false" href="">Жесткое завершение</button>
                </form>
            </div>
    {% endif %}
            <div class="add_block_content">
                {% include 'orders/order_prod_add.html' %}
            </div>
        </div>

{#    {% if request.session.pk %}#}
{#        <div id="add_block_add" class="add_block">#}
{#        <div class="add_block_content">#}
{#            <h1>Создаем новый заказ</h1>#}
{#            {% include 'orders/add_order_adm.html' %}#}
{##}
{#        </div>#}
{#    </div>#}
{#    {% else %}#}
        <div id="add_block_add" class="add_block hidediv">
        <div class="add_block_content">
            <h1>Создаем новый заказ</h1>
            {% include 'orders/add_order_adm.html' %}

        </div>
    </div>
{#    {% endif %}#}

{% endblock %}

templates/orders/user_orders.html
{% extends 'wrapper.html' %}
{% load static %}
{% load i18n %}

{% block user_content %}
    <div class="col-7">
        <div class="prod-list">
        <h2>товар в заказе № {{ elem_id }} Ваш заказ
                {% if status.status_ord.status_name == "created" %}
                    ожидает обработки. <br> Подожите пжлста. Мы Вам скоро перезвоним.</h2>
                {% else %}
                    {{ status.status_ord }} </h2><br>
                {% endif %}
                {% for elem in product_in_users_order %}
                    <div class="us-prod-ord">
                        <a href="{% url 'product' elem.product_id %}">
                            <img src="{{ elem.image }}" class="img-in-order">
                            {{ elem.product_name }}| размер
                            "{{ elem.sizes }}"
                            | {{ elem.nmb }} шт | по
                            {{ elem.price_per_item }} руб.
                        </a>
                    </div>
                {% endfor %}
            </div>
{#        </div>#}
    </div>
{% endblock %}